[versions]
kotlin = "1.7.10"

[libraries]
mockk = { module = "io.mockk:mockk", version = "1.12.4" }
junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.19" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.3" }

[bundles]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm",  version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
