[versions]
kotlin = "1.7.10"

hoplite = "2.8.2"

[libraries]
mockk = { module = "io.mockk:mockk", version = "1.12.4" }
junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.19" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.3" }

hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }

[bundles]
hoplite = [ "hoplite-core", "hoplite-hocon" ]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm",  version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
