[versions]
kotlin = "2.2.21"

hoplite = "2.8.2"

ktor = "3.2.3"

[libraries]
mockk = { module = "io.mockk:mockk", version = "1.14.6" }
junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.19" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }

valiktor-core = { module = "org.valiktor:valiktor-core", version = "0.12.0" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

skrapeit = { module = "it.skrape:skrapeit", version = "1.3.0-alpha.1" }

google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version = "1.37.1"}
google-api-client = { module = "com.google.api-client:google-api-client", version = "2.7.2" }
google-api-services-sheets = { module = "com.google.apis:google-api-services-sheets", version = "v4-rev20250211-2.0.0" }

kmongo-serialization = { module = "org.litote.kmongo:kmongo-serialization", version = "4.5.0" }

tika-core = { module = "org.apache.tika:tika-core", version = "3.2.3" }
html-sanitizer = { module = "com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer", version = "20240325.1" }

clikt = { module = "com.github.ajalt.clikt:clikt", version = "3.4.0" }

javax-mail = { module = "javax.mail:mail", version = "1.5.0-b01" }

[bundles]
ktor-client = [
  "ktor-client-core",
  "ktor-client-cio",
  "ktor-client-content-negotiation",
  "ktor-serialization-kotlinx-json",
]
ktor-server = [
  "ktor-server-content-negotiation",
  "ktor-server-core",
  "ktor-server-cors",
  "ktor-server-auth",
  "ktor-server-auth-jwt",
  "ktor-server-netty",
  "ktor-server-call-logging",
  "ktor-serialization-kotlinx-json",
]
ktor-server-test = [
  "ktor-server-test-host",
]
hoplite = [ "hoplite-core", "hoplite-hocon" ]
google-sheets = [ "google-auth-library-oauth2-http", "google-api-client", "google-api-services-sheets" ]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm",  version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.0.0" }
